services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"   # UI: http://localhost:15672 (guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: ./worker
    environment:
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
      - WORKER_CONCURRENCY=10
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: 3   # levanta 3 containers worker
